/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arsene' at '24/12/16 22:26' with Gradle 2.14.1
 *
 * @author Arsene, @date 24/12/16 22:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
